#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDItKKkp6HIcCHXSGFERkiPGeHXCWZGBjYog6m0Ylu9ShrsdeMdtBpRkwRIDjGtaOwv8/sHYgqecRRtCW+Jvs4PXxa9EvyQcE9a+9Uu5F9jiQdGZHgXq5N9WLq1gNdLn6ofolHKZVgCLMDXkJWRBE0EwJKUd05WnG/v/UGEcb2R0noS3uor00Hz3BECvyyEOWpxue7ul9aJxflMr4RP6Wn/qIHLQ03saeEKhwZWeDk2X5CMKR8Il8QW952ctd7G/RBFIWeaBsYq8eHBYlPzqhjluRppGq5q9WiHbhrOBHuQkVhucm9wrarIQqJuBXJN7nuwBkfOisiketX/IUOKqrkJ cselbert@swankmp.net
